---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-rbac-sync.fullname" . }}-account
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "argo-rbac-sync.fullname" . }}-role-namespaced
  namespace: {{ .Release.Namespace }}
rules:

  - apiGroups: [""]
    resources: [configmaps]
    verbs: [list, patch, get]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "argo-rbac-sync.fullname" . }}-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argo-rbac-sync.fullname" . }}-role-namespaced
subjects:
  - kind: ServiceAccount
    name: {{ include "argo-rbac-sync.fullname" . }}-account